version: '2'

services:
  postgresql:
    image: postgres:13-alpine
    restart: unless-stopped
    container_name: postgresql
    hostname: postgresql
    environment:
      POSTGRES_PASSWORD: bitcoin_indexer
      PS_DATABASES: bitcoin_indexer
    volumes:
      - /srv/blockchain/psql/data:/var/lib/postgresql/data
      - /srv/blockchain/psql/backup:/backup
      - ./init-create-dbs.sh:/docker-entrypoint-initdb.d/init-create-dbs.sh
    ports:
      - 5432:5432
    networks:
      - infranet
  indexer:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    container_name: indexer
    # entrypoint: sleep
    # command: "1000"
    hostname: indexer
    env_file:
      - ../.env
    networks:
      - infranet

networks:
  infranet:
    external: true
