#!/bin/bash
set -e

for DBNAME in $PS_DATABASES; do
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE $DBNAME;
    GRANT ALL PRIVILEGES ON DATABASE $DBNAME TO "$POSTGRES_USER";
EOSQL
    done
